/* global L, d3, APP_CONFIG */
const state={allFeatures:[],residentialFeatures:[],p95Total:1,baseBounds:null};
const map=L.map("map",{center:[40.7831,-73.9712],zoom:12,preferCanvas:false,zoomControl:true});
L.tileLayer("https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png",{attribution:"&copy; OpenStreetMap contributors &copy; CARTO",subdomains:"abcd",maxZoom:20,crossOrigin:true}).addTo(map);
const polygonLayer=L.geoJSON(null,{style:{color:"rgba(255, 250, 240, 0.45)",weight:.65,opacity:.85,fillColor:"rgba(255,255,255,0.015)",fillOpacity:.015}}).addTo(map);
const markerLayer=L.layerGroup().addTo(map);
const tooltip=L.tooltip({permanent:false,direction:"top",offset:[0,-8],className:"tooltip-card",opacity:1});
function num(v){const n=Number(v);return Number.isFinite(n)?n:0}function fmt(v){return Math.round(num(v)).toLocaleString()}function pct(v,t){return t?`${(v/t*100).toFixed(1)}%`:"0.0%"}
function norm(v){if(v===null||v===undefined)return null;const s=String(v).trim();return s===""?null:s}
function getValues(p={}){const f=APP_CONFIG.fields;const incomeRestricted=num(p[f.incomeRestricted]);const nycha=num(p[f.nycha]);const rentStabilized=num(p[f.rentStabilized]);const other=num(p[f.other]);return{incomeRestricted,nycha,rentStabilized,other,total:incomeRestricted+nycha+rentStabilized+other}}
function getBlockLabel(p={}){const f=APP_CONFIG.fields;return p[f.block]??p[f.objectId]??"Unknown"}function getCd(p={}){return norm(p[APP_CONFIG.fields.communityDistrict])}function getNeighborhood(p={}){return norm(p[APP_CONFIG.fields.neighborhood])}
function zoomScale(){const z=map.getZoom();if(z<=10)return .16;if(z===11)return .23;if(z===12)return .33;if(z===13)return .48;if(z===14)return .68;if(z===15)return .92;if(z===16)return 1.15;return 1.38}
function markerRadius(total){const minR=2.5,maxR=22;const base=minR+Math.sqrt(Math.min(total,state.p95Total)/state.p95Total)*(maxR-minR);return Math.max(2,base*zoomScale())}
function showPieSlices(){return document.getElementById("togglePie").checked&&map.getZoom()>=12}
function centroidLatLng(feature){const layer=L.geoJSON(feature);const b=layer.getBounds();if(b.isValid())return b.getCenter();const c=feature.geometry&&feature.geometry.coordinates;if(feature.geometry&&feature.geometry.type==="Point")return L.latLng(c[1],c[0]);return null}
function makeMarkerIcon(values){const r=markerRadius(values.total),size=Math.ceil(r*2+5),center=size/2;const data=[{value:values.incomeRestricted,color:APP_CONFIG.colors.incomeRestricted},{value:values.rentStabilized,color:APP_CONFIG.colors.rentStabilized},{value:values.nycha,color:APP_CONFIG.colors.nycha},{value:values.other,color:APP_CONFIG.colors.other}].filter(d=>d.value>0);let svg;if(!showPieSlices()||data.length===0){svg=`<svg class="pie-marker" width="${size}" height="${size}" viewBox="0 0 ${size} ${size}" xmlns="http://www.w3.org/2000/svg"><circle cx="${center}" cy="${center}" r="${r}" fill="${APP_CONFIG.colors.neutralCircle}" stroke="${APP_CONFIG.colors.outline}" stroke-width="0.8"/></svg>`}else{const pie=d3.pie().value(d=>d.value).sort(null)(data);const arc=d3.arc().innerRadius(0).outerRadius(r);const paths=pie.map(s=>`<path d="${arc(s)}" fill="${s.data.color}"></path>`).join("");svg=`<svg class="pie-marker" width="${size}" height="${size}" viewBox="0 0 ${size} ${size}" xmlns="http://www.w3.org/2000/svg"><g transform="translate(${center},${center})">${paths}<circle cx="0" cy="0" r="${r}" fill="none" stroke="${APP_CONFIG.colors.outline}" stroke-width="0.9"/></g></svg>`}return L.divIcon({html:svg,className:"",iconSize:[size,size],iconAnchor:[center,center],popupAnchor:[0,-r]})}
function popupHtml(p,v){const labels=APP_CONFIG.labels;return`<div class="popup-title">Block ${getBlockLabel(p)}</div><div class="popup-subtitle">Community District: ${getCd(p)??"—"}<br>Neighborhood: ${getNeighborhood(p)??"—"}</div><table class="popup-table"><tr><td>Total mapped units</td><td>${fmt(v.total)}</td></tr><tr><td>${labels.incomeRestricted}</td><td>${fmt(v.incomeRestricted)} (${pct(v.incomeRestricted,v.total)})</td></tr><tr><td>${labels.rentStabilized}</td><td>${fmt(v.rentStabilized)} (${pct(v.rentStabilized,v.total)})</td></tr><tr><td>${labels.nycha}</td><td>${fmt(v.nycha)} (${pct(v.nycha,v.total)})</td></tr><tr><td>${labels.other}</td><td>${fmt(v.other)} (${pct(v.other,v.total)})</td></tr></table>`}
function tooltipHtml(p,v){return`<strong>Block ${getBlockLabel(p)}</strong>${fmt(v.total)} total mapped units${getNeighborhood(p)?`<br>${getNeighborhood(p)}`:""}`}
function passesFilters(feature){const p=feature.properties||{},v=getValues(p);if(v.total<=0)return false;const cd=document.getElementById("cdFilter").value;const n=document.getElementById("neighborhoodFilter").value;if(cd!=="all"&&getCd(p)!==cd)return false;if(n!=="all"&&getNeighborhood(p)!==n)return false;return true}
function getSelectedArea(){const n=document.getElementById("neighborhoodFilter").value;const cd=document.getElementById("cdFilter").value;if(n!=="all")return{type:"Neighborhood",value:n,predicate:f=>getNeighborhood(f.properties||{})===n};if(cd!=="all")return{type:"Community District",value:cd,predicate:f=>getCd(f.properties||{})===cd};return null}
function selectedAreaTotals(){const area=getSelectedArea();if(!area)return null;const totals={incomeRestricted:0,rentStabilized:0,nycha:0,other:0,total:0,residentialBlocks:0};state.residentialFeatures.forEach(f=>{if(!area.predicate(f))return;const v=getValues(f.properties||{});totals.incomeRestricted+=v.incomeRestricted;totals.rentStabilized+=v.rentStabilized;totals.nycha+=v.nycha;totals.other+=v.other;totals.residentialBlocks+=1});totals.total=totals.incomeRestricted+totals.rentStabilized+totals.nycha+totals.other;return{area,values:totals}}
function renderAreaPanel(){const result=selectedAreaTotals();const panel=document.getElementById("areaPanel"),chart=document.getElementById("areaPieChart"),breakdown=document.getElementById("areaBreakdown");chart.innerHTML="";breakdown.innerHTML="";if(!result){panel.classList.add("is-hidden");return}panel.classList.remove("is-hidden");document.getElementById("areaTitle").textContent=result.area.type==="Community District"?`Community District ${result.area.value}`:result.area.value;document.getElementById("areaSubtitle").textContent=`${result.area.type} · ${fmt(result.values.total)} total mapped units`;document.getElementById("areaResidentialBlocks").textContent=fmt(result.values.residentialBlocks);document.getElementById("areaAvgUnits").textContent=fmt(result.values.residentialBlocks?result.values.total/result.values.residentialBlocks:0);const labels=APP_CONFIG.labels;const data=[{label:labels.incomeRestricted,value:result.values.incomeRestricted,color:APP_CONFIG.colors.incomeRestricted},{label:labels.rentStabilized,value:result.values.rentStabilized,color:APP_CONFIG.colors.rentStabilized},{label:labels.nycha,value:result.values.nycha,color:APP_CONFIG.colors.nycha},{label:labels.other,value:result.values.other,color:APP_CONFIG.colors.other}].filter(d=>d.value>0);const width=124,height=124,radius=58;const svg=d3.select(chart).append("svg").attr("width",width).attr("height",height);const g=svg.append("g").attr("transform",`translate(${width/2},${height/2})`);const pie=d3.pie().value(d=>d.value).sort(null);const arc=d3.arc().innerRadius(24).outerRadius(radius);g.selectAll("path").data(pie(data)).join("path").attr("d",arc).attr("fill",d=>d.data.color).attr("stroke","#fffdf7").attr("stroke-width",1.5);g.append("text").attr("text-anchor","middle").attr("dy","-.1em").attr("fill","#1e2329").attr("font-size",14).attr("font-weight",820).text(fmt(result.values.total));g.append("text").attr("text-anchor","middle").attr("dy","1.25em").attr("fill","#66707a").attr("font-size",10).text("units");data.forEach(d=>{const row=document.createElement("div");row.className="breakdown-row";row.innerHTML=`<span class="dot" style="background:${d.color}"></span><span>${d.label}</span><strong>${pct(d.value,result.values.total)}</strong>`;breakdown.appendChild(row)})}
function render(){markerLayer.clearLayers();polygonLayer.clearLayers();const showPolygons=document.getElementById("togglePolygons").checked;let visibleUnits=0;const visibleFeatures=[];for(const feature of state.residentialFeatures){if(!passesFilters(feature))continue;const p=feature.properties||{},v=getValues(p),latlng=centroidLatLng(feature);if(!latlng)continue;visibleUnits+=v.total;visibleFeatures.push(feature);const marker=L.marker(latlng,{icon:makeMarkerIcon(v),riseOnHover:true});marker.bindPopup(popupHtml(p,v),{maxWidth:340});marker.on("mouseover",()=>{tooltip.setContent(tooltipHtml(p,v));tooltip.setLatLng(latlng);tooltip.addTo(map)});marker.on("mouseout",()=>map.removeLayer(tooltip));markerLayer.addLayer(marker)}if(showPolygons)polygonLayer.addData({type:"FeatureCollection",features:visibleFeatures});document.getElementById("visibleUnits").textContent=fmt(visibleUnits);const n=document.getElementById("neighborhoodFilter").value,cd=document.getElementById("cdFilter").value;document.getElementById("visibleContext").textContent=n!=="all"?"Within selected Neighborhood":cd!=="all"?"Within selected Community District":"Across visible residential blocks";renderAreaPanel()}
function populateFilters(){const cds=new Set(),neighborhoods=new Set();state.residentialFeatures.forEach(f=>{const p=f.properties||{},cd=getCd(p),n=getNeighborhood(p);if(cd)cds.add(cd);if(n)neighborhoods.add(n)});const cdSelect=document.getElementById("cdFilter");Array.from(cds).sort((a,b)=>Number(a)-Number(b)).forEach(cd=>{const o=document.createElement("option");o.value=cd;o.textContent=`CD ${cd}`;cdSelect.appendChild(o)});const nSelect=document.getElementById("neighborhoodFilter");Array.from(neighborhoods).sort((a,b)=>a.localeCompare(b)).forEach(n=>{const o=document.createElement("option");o.value=n;o.textContent=n;nSelect.appendChild(o)})}
function zoomToSelectedArea(){const area=getSelectedArea();if(!area)return;const areaFeatures=state.residentialFeatures.filter(area.predicate);const bounds=L.geoJSON({type:"FeatureCollection",features:areaFeatures}).getBounds();if(bounds.isValid())map.fitBounds(bounds.pad(.12))}
async function loadData(){const loading=document.getElementById("loading");try{const response=await fetch(APP_CONFIG.dataUrl);if(!response.ok)throw new Error(`HTTP ${response.status}`);const geojson=await response.json();state.allFeatures=geojson.features||[];state.residentialFeatures=state.allFeatures.filter(f=>getValues(f.properties||{}).total>0);const totals=state.residentialFeatures.map(f=>getValues(f.properties||{}).total).filter(t=>t>0).sort((a,b)=>a-b);state.p95Total=totals.length?totals[Math.floor(totals.length*.95)]:1;state.baseBounds=L.geoJSON({type:"FeatureCollection",features:state.residentialFeatures}).getBounds();if(state.baseBounds.isValid())map.fitBounds(state.baseBounds.pad(.08));populateFilters();render()}catch(e){console.error(e);loading.textContent="Could not load data/manhattan_blocks.geojson. Use a local server or GitHub Pages."}finally{if(loading.textContent==="Loading housing data…")loading.classList.add("is-hidden")}}
document.getElementById("cdFilter").addEventListener("change",()=>{render();zoomToSelectedArea()});document.getElementById("neighborhoodFilter").addEventListener("change",()=>{render();zoomToSelectedArea()});document.getElementById("togglePie").addEventListener("change",render);document.getElementById("togglePolygons").addEventListener("change",render);map.on("zoomend",render);document.getElementById("resetView").addEventListener("click",()=>{document.getElementById("cdFilter").value="all";document.getElementById("neighborhoodFilter").value="all";document.getElementById("togglePie").checked=true;document.getElementById("togglePolygons").checked=true;render();if(state.baseBounds&&state.baseBounds.isValid())map.fitBounds(state.baseBounds.pad(.08))});loadData();